NAME_MAPPER = {
    '경주일': 'race_date',
    '경주번호': 'race_number',
    '요일': 'race_dow',
    '시작시간': 'race_time',
    '총출전두수': 'race_horse_cout',
    '날씨': 'weather',
    '주로습도': 'track_humidity',
    '주로상태': 'track_condition',
    '경주등급': 'race_level',
    '경주거리': 'race_dist',
    '경주의격': 'race_title',
    '출전조건': 'race_condition',
    '1위상금': 'prize_1',
    '2위상금': 'prize_2',
    '3위상금': 'prize_3',
    '4위상금': 'prize_4',
    '5위상금': 'prize_5',
    '말아이디': 'horse_id',
    '마명': 'horse_name',
    '말 성별': 'horse_sex',
    '말 나이': 'horse_age',
    '기수아이디': 'jockey_id',
    '기수명': 'jockey_name',
    '마주아이디': 'owner_id',
    '마주명': 'owner_name',
    '말 출생국': 'horse_lob',
    '조교사아이디': 'trainer_id',
    '조교사명': 'trainer_name',
    '소속조번': 'group_number',
    '부담중량': 'load_weight',
    '말 몸무게': 'horse_weight',
    '단승식배당률': 'odd_single',
    '연승식배당률': 'odd_double',
    '순위': 'standing',
    '경주기록': 'rec_final',
    '통과누적기록S-1F지점': 'rec_s1f',
    '펄롱타임3F-G': 'rec_3fg',
    '펄롱타임1F-G': 'rec_1fg',
    '통과누적기록1코너지점': 'rec_1c',
    '통과누적기록2코너지점': 'rec_2c',
    '통과누적기록3코너지점': 'rec_3c',
    '통과누적기록4코너지점': 'rec_4c',
    '부담중량 종류': 'load_kind',
}
